name: "Save secrets variables"

on: [push, pull_request]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Get secret from base64
      env:
          KEYSTORE_BASE64: ${{ secrets.TEST_1 }}
      run: |
          echo import certificate from secrets and regenerate the file
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore
