name: "Save secrets variables"

on: [push, pull_request]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Get secret from base64
      env:
          KEYSTORE_BASE64: ${{ secrets.TEST_1 }}
      run: |
          echo ${{secrets.TEST_1}} | sed 's/./& /g'
